#############################################################################
# Generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#  Dec 02, 2021 02:10:19 PM IST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m49" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1536x801+-32+-23
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1540 845
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    label $top.lab45 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Sitka Small} -size 18 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief sunken \
        -text {Shallow-water Image Enhancement Using Relative Global Histogram Stretching Based on Adaptive Parameter Acquisition} \
        -wraplength 600 
    vTcl:DefineAlias "$top.lab45" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab50 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family Tahoma -size 16 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Input Image} 
    vTcl:DefineAlias "$top.lab50" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab51 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family Tahoma -size 16 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Contrast corrected Image} 
    vTcl:DefineAlias "$top.lab51" "Label2_1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab52 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family Tahoma -size 16 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Color corrected Image} 
    vTcl:DefineAlias "$top.lab52" "Label2_1_1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but53 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -borderwidth 5 \
        -disabledforeground #a3a3a3 \
        -font {-family {Lucida Console} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -padx 2 -pady 2 -text {Upload Image} 
    vTcl:DefineAlias "$top.but53" "UploadImage" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab46 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) -relief sunken -text {image
} 
    vTcl:DefineAlias "$top.lab46" "InputImage" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab47 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) -relief sunken -text image 
    vTcl:DefineAlias "$top.lab47" "ContrastCorrImage" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab48 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) -relief sunken -text image 
    vTcl:DefineAlias "$top.lab48" "ColorCorrImage" vTcl:WidgetProc "Toplevel1" 1
    menu $top.m49 \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font TkMenuFont -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab45 \
        -in $top -x 0 -relx 0.28 -y 0 -rely 0.037 -width 0 -relwidth 0.432 \
        -height 0 -relheight 0.151 -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 0 -relx 0.117 -y 0 -rely 0.3 -width 0 -relwidth 0.126 \
        -height 0 -relheight 0.052 -anchor nw -bordermode ignore 
    place $top.lab51 \
        -in $top -x 0 -relx 0.404 -y 0 -rely 0.3 -width 0 -relwidth 0.178 \
        -height 0 -relheight 0.052 -anchor nw -bordermode ignore 
    place $top.lab52 \
        -in $top -x 0 -relx 0.736 -y 0 -rely 0.3 -width 0 -relwidth 0.165 \
        -height 0 -relheight 0.051 -anchor nw -bordermode ignore 
    place $top.but53 \
        -in $top -x 0 -relx 0.13 -y 0 -rely 0.824 -width 127 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab46 \
        -in $top -x 0 -relx 0.046 -y 0 -rely 0.362 -width 0 -relwidth 0.28 \
        -height 0 -relheight 0.437 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -relx 0.358 -y 0 -rely 0.362 -width 0 -relwidth 0.28 \
        -height 0 -relheight 0.437 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -relx 0.671 -y 0 -rely 0.362 -width 0 -relwidth 0.28 \
        -height 0 -relheight 0.437 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}



set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

